spring:
  application:
    name: desafio-anota-ai
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-catalog
      username: admin
      password: admin
      authentication-database: admin
aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}
  sns:
    topic:
      catalog:
        arn: ${AWS_SNS_ARN}